Version 7.3 final release

diff --git a/piradio.postinst b/piradio.postinst
--- a/piradio.postinst
+++ b/piradio.postinst
@@ -1,7 +1,7 @@
 #!/bin/bash 
-set -e
+#set -e
 # Radio daemon post install script
-# $Id: piradio.postinst,v 1.6 2021/09/30 08:03:28 bob Exp $
+# $Id: piradio.postinst,v 1.9 2021/11/01 14:16:27 bob Exp $
 # Support for Pulseaudio added
 
 # File locations
@@ -18,6 +18,7 @@ DEFAULTRCS=/etc/default/rcS
 EQUALIZERCMD=equalizer.cmd
 LOGDIR=/var/log/radiod
 PIDDIR=/var/run/radiod
+MPD_PLAYLISTS=/var/lib/mpd/playlists
 
 # Configure radio but skip any other package installation or removal
 # with the -s flag
@@ -31,10 +32,15 @@ then
 fi
 
 # Set up a default radio variant
-sudo mkdir -p ${RADIOLIB}
+if [[ ! -d ${RADIOLIB} ]];then
+    sudo mkdir -p ${RADIOLIB}
+fi
 
 # Set daemon startup defaults
 sudo systemctl enable radiod.service
+if [[ $? != 0 ]]; then
+	echo "Error: Failed to enable radiod.service"
+fi
 
 # Ensure owner is pi
 sudo chown -R pi:pi ${DIR}
@@ -121,6 +127,35 @@ if [[ ! -f "${RADIOLIB}/stationlist" ]]; then
 	${DIR}/create_stations.py --no_delete 2>&1 > ${DIR}/playlists.log
 	echo "Done: See ${DIR}/playlists.log for information about playlists created"
 	echo
+fi
+
+# Rename old style radio playlists (remove '_' at start of file name)
+ls ${MPD_PLAYLISTS}/_* >/dev/null 2>&1
+if [[ $? == 0 ]]; then
+    echo
+    echo "Old style radio playlists found in ${MPD_PLAYLISTS}"
+    for file in ${MPD_PLAYLISTS}/_*
+    do
+        file_name=$(basename ${file})
+        blank=''
+        new_name=${file_name/_/${blank}}
+        cmd="sudo mv ${MPD_PLAYLISTS}/${file_name} ${MPD_PLAYLISTS}/${new_name}"
+        echo ${cmd}
+        ${cmd}
+        if [[ $? == 0 ]]; then
+            echo "Playlist ${file_name} renamed as ${new_name}"
+        else
+            echo "Error: Failed to rename ${file_name} as ${new_name}"
+        fi
+    done
+
+fi
+
+# Remove leading '_' from startup playlist name
+grep '^startup=_' ${CONFIGFILE} 
+if [[ $? == 0 ]]; then
+    echo "Removing leading underscore from startup playlist paramter in ${CONFIGFILE}" 
+    sudo sed -i -e 's/^startup=_/startup=/' ${CONFIGFILE}
 fi
 
 # Force file checks on reboot
